"""user password text

Revision ID: 51fcee167ef7
Revises: 46ceaf6798e9
Create Date: 2015-08-21 01:54:01.020883

"""

# revision identifiers, used by Alembic.
revision = '51fcee167ef7'
down_revision = '46ceaf6798e9'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    ### end Alembic commands ###
